apiVersion: v1
kind: Service
metadata:
  name: cstar-mock-s3-srv # name will be the -... three letters abbreviation of the Kind
  namespace: default
  labels:
    run: cstar-mock-s3 # we label run: ... all the resources that run a particular service (here cstar-mock-s3)
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    run: cstar-mock-s3 # this will select from the template.spec.metadata.labels (the pod)
---
apiVersion: v1
kind: Service
metadata:
  name: cstar-mock-s3-console-srv
  namespace: default
  labels:
    run: cstar-mock-s3 # we label run: ... all the resources that run a particular service (here cstar-mock-s3)
spec:
  type: LoadBalancer
  ports:
    - port: 9001
      protocol: TCP
      targetPort: 9001
  selector:
    run: cstar-mock-s3 # this will select from the template.spec.metadata.labels (the pod)    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cstar-mock-s3-dep
  namespace: default
  labels:
    run: cstar-mock-s3
spec:
  replicas: 1
  selector:
    matchLabels:
      run: cstar-mock-s3
  template:
    metadata:
      labels:
        run: cstar-mock-s3
    spec:
      volumes:
        # Those volumes are for development, it allow REPL dev from local build
        - name: cstar-mock-s3-data-folder
          hostPath:
            path: '{{dir_abs}}/services/mock-s3/.data'
            type: DirectoryOrCreate
      containers:
        - image: "localhost:5000/cstar-mock-s3:{{image_tag}}"
          imagePullPolicy: Always
          name: cstar-mock-s3-ctn
          env:
            - name: service_name
              value: mock-s3        
            - name: RUSTFS_ACCESS_KEY
              value: 'rustfsadmin'        
            - name: RUSTFS_SECRET_KEY
              value: 'rustfsadmin' 
          ports:
            - containerPort: 9000
              protocol: TCP
            - containerPort: 9001
              protocol: TCP  
          volumeMounts:
            - mountPath: /data
              name: cstar-mock-s3-data-folder
      restartPolicy: Always

