import chokidar from 'chokidar';
import { glob } from 'glob';
import { bundle } from 'lightningcss';
import debounce from 'lodash.debounce';
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve, sep } from "node:path";

const service = 'admin-server';

// Configuration
const OUTPUT_FILE = `../../services/${service}/web-folder/css/all-bundle.css`;
const WATCH_GLOB = ['./css/', "../_common/css/"];
const cssOutputDir = dirname(OUTPUT_FILE);

const generateEntry = async () => {
  const files = await glob(['css/**/*.css']);

  const imports = files.map((file) => {
    const relativePath = relative('.', file);
    const normalizedPath = relativePath.split(sep).join('/');
    return `@import './${normalizedPath}';`;
  }).join('\n');

  const entryContent = `
/* Auto-generated by lightning config
   DO NOT EDIT THIS FILE MANUALLY */
${imports}
`;

  const entryPath = resolve('./.lightning.entry_aggregate.css');
  writeFileSync(entryPath, entryContent);

  console.log(`Generated entry file: ${files.length} modules aggregated.`);
  
  return entryPath;
};

const entryFile = await generateEntry();


// Build function
async function build() {
  console.log('Building CSS...');
  try {
    let {code, map} = await bundle({
      filename: entryFile,
      sourceMap:true,
      projectRoot: process.cwd(), 
    });
    mkdirSync(cssOutputDir, { recursive: true });
    writeFileSync(OUTPUT_FILE, code);
    writeFileSync(join(cssOutputDir, "all-bundle.css.map"), map);

    console.log(`Built: ${OUTPUT_FILE}`);
  } catch (error) {
    console.error('Build failed:', error);
  }
}

// Run build immediately
build();

// Check if -w flag is present
const isWatch = process.argv.includes('-w');

if (isWatch) {
  console.log('Watching for css changes...');
  
  // Initialize watcher
  const watcher = chokidar.watch(WATCH_GLOB, { ignoreInitial: true });

  const cr = debounce(async () => {
    build();
  }, 500);

  watcher.on('change', (path) => {
    cr();
  });

  watcher.on('add', (path) => {
    cr();
  });
}