import { execSync } from 'child_process';
import { glob } from 'glob';
import { writeFileSync } from 'node:fs';
import { relative, resolve, sep } from 'node:path';
import { defineConfig } from 'rolldown';

const service = "admin-server";

// -------------------------------------------------------
// 1. Type Checking (tsc --noEmit)
// -------------------------------------------------------
const runTypeCheck = () => {
  const isWatch = process.argv.includes('--watch') || process.argv.includes('-w');

  if (!isWatch) {
    try {
      console.log('Running type check...');
      execSync('npx tsc --noEmit', { stdio: 'inherit' });
      console.log('Type check passed.');
    } catch (error) {
      console.error('\nType check failed. Build stopped.');
      process.exit(1);
    }
  } else {
    console.log('Watch mode: Skipping type check for performance.');
  }
};

runTypeCheck();

// -------------------------------------------------------
// 2. Dynamic Entry Generation (Glob)
// -------------------------------------------------------
const generateEntry = async () => {
  const files = await glob('src/**/*.ts');

  const imports = files.map((file) => {
    const relativePath = relative('.', file);
    const normalizedPath = relativePath.split(sep).join('/');
    return `import './${normalizedPath}';`;
  }).join('\n');

  const entryContent = `
// Auto-generated by rolldown config
// DO NOT EDIT THIS FILE MANUALLY
${imports}
`;

  const entryPath = resolve('./.rolldown.entry_aggregate.ts');
  writeFileSync(entryPath, entryContent);

  console.log(`Generated entry file: ${files.length} modules aggregated.`);
  
  return entryPath;
};

const entryFile = await generateEntry();

// -------------------------------------------------------
// 3. Rolldown Configuration
// -------------------------------------------------------
export default defineConfig([
  // app
  {
    input: entryFile,
    external: ['handlebars'],
    output: {
      file: `../../services/${service}/web-folder/js/app-bundle.js`,
      format: 'iife',
      name: 'app',
      globals: {
        handlebars: 'Handlebars'
      },
      sourcemap: true
    },
  }
]);
